"""Router modules for API endpoints."""
from . import (
    attendance,
    auth,
    branches,
    class_types,
    dashboard,
    feedback,
    invoices,
    leads,
    members,
    membership_tracking,
    notifications,
    organizations,
    payments,
    plans,
    reminders,
    sessions,
    staff,
    subscriptions,
    trainer,
    workouts,
)

__all__ = [
    "auth",
    "organizations",
    "branches",
    "staff",
    "leads",
    "members",
    "plans",
    "subscriptions",
    "payments",
    "sessions",
    "class_types",
    "attendance",
    "dashboard",
    "feedback",
    "invoices",
    "notifications",
    "reminders",
    "membership_tracking",
    "trainer",
    "workouts",
]
